// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class CONSTANTS
{
        public const string achievement_over_9000 = "CgkIxs2M-tEfEAIQDA"; // <GPGSID>
        public const string achievement_much_exploit_such_wow_you_found_me = "CgkIxs2M-tEfEAIQEA"; // <GPGSID>
        public const string achievement_call_the_police_i_am_going_crazy = "CgkIxs2M-tEfEAIQBw"; // <GPGSID>
        public const string achievement_going_the_distance = "CgkIxs2M-tEfEAIQDg"; // <GPGSID>
        public const string achievement_commercial_break = "CgkIxs2M-tEfEAIQFA"; // <GPGSID>
        public const string achievement_propaganda = "CgkIxs2M-tEfEAIQFg"; // <GPGSID>
        public const string achievement_better_than_the_devs = "CgkIxs2M-tEfEAIQBg"; // <GPGSID>
        public const string leaderboard_lives = "CgkIxs2M-tEfEAIQCQ"; // <GPGSID>
        public const string achievement_the_explorer = "CgkIxs2M-tEfEAIQFw"; // <GPGSID>
        public const string leaderboard_hardcore = "CgkIxs2M-tEfEAIQGA"; // <GPGSID>
        public const string achievement_getting_a_wardrobe = "CgkIxs2M-tEfEAIQEg"; // <GPGSID>
        public const string achievement_television = "CgkIxs2M-tEfEAIQFQ"; // <GPGSID>
        public const string achievement_what_the_devil = "CgkIxs2M-tEfEAIQCw"; // <GPGSID>
        public const string achievement_this_wasnt_planned = "CgkIxs2M-tEfEAIQEw"; // <GPGSID>
        public const string achievement_warming_up = "CgkIxs2M-tEfEAIQAw"; // <GPGSID>
        public const string achievement_we_can_go_higher = "CgkIxs2M-tEfEAIQBA"; // <GPGSID>
        public const string achievement_this_is_good = "CgkIxs2M-tEfEAIQCg"; // <GPGSID>
        public const string achievement_fancy_now = "CgkIxs2M-tEfEAIQEQ"; // <GPGSID>
        public const string achievement_yes_theres_more = "CgkIxs2M-tEfEAIQDw"; // <GPGSID>
        public const string leaderboard_casual = "CgkIxs2M-tEfEAIQCA"; // <GPGSID>
        public const string achievement_hardest_30_seconds_of_my_life = "CgkIxs2M-tEfEAIQDQ"; // <GPGSID>
        public const string achievement_getting_the_hang_of_it = "CgkIxs2M-tEfEAIQBQ"; // <GPGSID>

}

