// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class MYCONSTANTS
{
        public const string leaderboard_casual = "CgkIxs2M-tEfEAIQCA"; // <GPGSID>
        public const string achievement_rty = "CgkIxs2M-tEfEAIQBg"; // <GPGSID>
        public const string achievement_bvc = "CgkIxs2M-tEfEAIQBw"; // <GPGSID>
        public const string achievement_dsa = "CgkIxs2M-tEfEAIQAw"; // <GPGSID>
        public const string achievement_hgf = "CgkIxs2M-tEfEAIQBQ"; // <GPGSID>
        public const string leaderboard_lives = "CgkIxs2M-tEfEAIQCQ"; // <GPGSID>
        public const string achievement_qwe = "CgkIxs2M-tEfEAIQBA"; // <GPGSID>

}

